{ pkgs, ... }:

let
  caelestia-to-wal = pkgs.writeShellScriptBin "caelestia-to-wal" ''
    exec ${pkgs.python3}/bin/python3 ${./scripts/caelestia-to-wal.py} "$@"
  '';

  caelestia-to-telegram = pkgs.writeShellScriptBin "caelestia-to-telegram" ''
    exec ${pkgs.python3}/bin/python3 ${./scripts/caelestia-to-telegram.py} "$@"
  '';
in
{
  home.packages = [
    pkgs.pywalfox-native
    caelestia-to-wal
    caelestia-to-telegram
  ];

  # Pywalfox native messaging host manifest
  home.file.".mozilla/native-messaging-hosts/pywalfox.json".text = builtins.toJSON {
    name = "pywalfox";
    description = "Automatically theme your browser using the colors generated by Pywal";
    path = "${pkgs.pywalfox-native}/bin/pywalfox";
    type = "stdio";
    allowed_extensions = [ "pywalfox@frewacom.org" ];
  };

  # Caelestia post-wallpaper-change hook
  home.file.".config/caelestia/cli.json".text = builtins.toJSON {
    wallpaper = {
      postHook = "caelestia-to-wal && caelestia-to-telegram";
    };
  };
}
