#!/usr/bin/env bash

status="$(cat "/sys/class/power_supply/BAT0/status")"
per="$(cat "/sys/class/power_supply/BAT0/capacity")"
governor="$(cat "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor")"
charging=""
icon=""
gov=""

if [ $per -gt 90 ]; then
    icon="󰣐"
elif [ $per -gt 60 ]; then
    icon="󰁿"
elif [ $per -gt 30 ]; then
    icon="󰁼"
elif [ $per -gt 10 ]; then
    icon="󰁺"
else
    icon="󰂎"
fi

if [ $status = "Charging" ]; then
    charging="⠀󱐋"
else
    charging=""
fi

if [ $governor = "powersave" ]; then
    gov="s"
elif [ $governor = "performance" ]; then
    gov="p"
fi

per=$per%
out="$icon$charging"

echo $gov $per $out | jq -R -s 'split(" ") | {gov: .[0], per: .[1], out: .[2]}'