#!/usr/bin/env bash

currentTheme=$(cat ~/.config/eww/consts/theme.txt)

hyprConfig=~/.config/hypr

themes=$(ls ~/.config/eww/themes)
themes=($themes)

themeName=$1
themePath=""

themePath=~/.config/eww/themes/$themeName

echo $themeName >~/.config/eww/consts/theme.txt

rm ~/.config/eww/scss/main.scss
ln -s $themePath/main.scss ~/.config/eww/scss/main.scss
cp $themePath/background.jpg $hyprConfig/background.jpg
cp $themePath/img.jpg $hyprConfig/img.jpg
cp $themePath/hypr-colors.conf $hyprConfig/hypr-colors.conf
cp $themePath/mako.conf ~/.config/mako/config

pkill eww
pkill eww
eww open bar

wal -n -i $themePath/background.jpg &

swww img $themePath/background.jpg --transition-type center

sleep 1

# makoctl reload

echo "Theme changed to $themeName"
