#!/usr/bin/env bash
governor="$(cat "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor")"

if [ $governor = "powersave" ]; then
    sudo cpupower frequency-set --governor performance
elif [ $governor = "performance" ]; then
    sudo cpupower frequency-set --governor powersave
fi

echo $governor