#!/bin/bash
IFS=$'\n'
set -f

SSIDS=$(nmcli -f SSID device wifi | sed '1d')
SSIDS=($SSIDS)

signals=$(nmcli -f SIGNAL device wifi | sed '1d')
signals=($signals)

networks=""

# cycle networks
for i in "${!signals[@]}"; do
    iconStr=""
    if [ "${signals[$i]}" -gt 80 ]; then
        iconStr="󰤨"
    elif [ "${signals[$i]}" -gt 60 ]; then
        iconStr="󰤥"
    elif [ "${signals[$i]}" -gt 40 ]; then
        iconStr="󰤢"
    elif [ "${signals[$i]}" -gt 20 ]; then
        iconStr="󰤟"
    else
        iconStr="󰤯"
    fi
    
    # trim SSID
    SSIDS[$i]=$(echo ${SSIDS[$i]} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

    # append to networks with keys
    networks+=("{\"name\":\"${SSIDS[$i]}\", \"icon\":\"${iconStr}\"},")

done

# remove duplicates SSIDS
networks=($(printf "%s\n" "${networks[@]}" | sort -u))

networks=$(printf '%s\n' "${networks[@]}")

# print networks as json using jq
echo "[${networks%?}]" | jq -c .

exit
