#!/usr/bin/env bash

string_to_find="with pkgs"
config_file="/home/nespoli/.dotfiles/nix/users.nix"
package=$(gum input --prompt '👾 ' --placeholder "What do you want to install")

if [ -z "$package" ]; then
    echo "No package provided"
    exit 1
fi

line_number=$(grep -n "$string_to_find" "$config_file" | head -n 1 | cut -d: -f1)

if [ -z "$line_number" ]; then
    echo "Error with config file: $config_file"
else
    sed -i "${line_number}a $package" "$config_file"
fi

echo "📝 Config file changed"
echo

gum spin --spinner dot --title "Installing ${package}..." -- nixos-rebuild switch

echo "✨ Done"