#!/usr/bin/env bash

# open multiple programs from an array without waiting for each to finish

# programs to open
declare -a programs=(
    "firefox"
    "telegram-desktop"
    "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
)

# open programs
for program in "${programs[@]}"; do
    $program &
done
