#!/usr/bin/env bash

output=$(wpctl get-volume @DEFAULT_SINK@)
volume=$(echo $output | awk '{print $2}')
mute_status=$(echo $output | awk '{print $3}')

if [ "$mute_status" = "[MUTED]" ]; then
    percentage=0
else
    percentage=$(awk "BEGIN {printf \"%.0f\", $volume*100}")
fi

echo "$percentage"