# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d8a917a8-9e45-4e8b-a3e9-37d96f4956a0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d8a917a8-9e45-4e8b-a3e9-37d96f4956a0".device = "/dev/disk/by-uuid/d8a917a8-9e45-4e8b-a3e9-37d96f4956a0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ECEC-9261";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f41d2b4a-3c3c-4be2-95fd-8156cab9c76b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
