"""Generate an Ayugram/Telegram Desktop .tdesktop-theme from caelestia colors."""
import io, json, os, subprocess, zipfile

raw = os.environ.get("SCHEME_COLOURS")
if raw:
    c = json.loads(raw)
else:
    data = json.loads(subprocess.check_output(["caelestia", "wallpaper", "--print"]))
    c = data["colours"]

def h(key, alpha=None):
    col = c[key]
    if alpha is not None:
        return f"#{col}{alpha:02x}"
    return f"#{col}"

# Semantic aliases
bg        = h("base")
bg2       = h("surfaceContainer")
bg3       = h("surfaceContainerHigh")
bg4       = h("surfaceContainerHighest")
sidebar   = h("base")
topbar    = h("surfaceContainerLow")
fg        = h("text")
fg2       = h("subtext1")
fg3       = h("subtext0")
accent    = h("primary")
accent2   = h("primaryDim")
msgIn     = h("surfaceContainer")
msgOut    = h("primaryContainer")
msgInFg   = h("onSurface")
msgOutFg  = h("onPrimaryContainer")
border    = h("outlineVariant")
danger    = h("error")
success   = h("kpositive")
badge     = h("primary")
badgeFg   = h("onPrimary")

palette = f"""
// Generated by caelestia-to-telegram

windowBg: {bg};
windowFg: {fg};
windowBgOver: {bg3};
windowBgRipple: {bg4};
windowFgOver: {fg};
windowSubTextFg: {fg2};
windowSubTextFgOver: {fg};
windowBoldFg: {fg};
windowBoldFgOver: {fg};
windowBgActive: {accent};
windowFgActive: {badgeFg};
windowActiveTextFg: {accent};
windowShadowFg: #00000000;
windowShadowFgFallback: {bg};
shadowFg: #00000018;
slideFadeOutBg: #0000007f;
slideFadeOutShadowFg: #000000;
imageBg: #000000;
imageBgTransparent: #ffffff;
activeLineFg: {accent};
activeLineFgError: {danger};
lightButtonBg: {bg};
lightButtonBgOver: {bg3};
lightButtonBgRipple: {bg4};
lightButtonFg: {accent};
lightButtonFgOver: {accent};
lightButtonBadgeFg: {badgeFg};
lightButtonBadgeBg: {badge};
attentionButtonFg: {danger};
attentionButtonFgOver: {danger};
attentionButtonBgOver: {bg3};
attentionButtonBgRipple: {bg4};
outlineButtonBg: {bg};
outlineButtonBgOver: {bg3};
outlineButtonOutlineFg: {accent};
outlineButtonBgRipple: {bg4};
menuBg: {bg2};
menuBgOver: {bg3};
menuBgRipple: {bg4};
menuIconFg: {fg2};
menuIconFgOver: {fg};
menuSubmenuArrowFg: {fg2};
menuFgDisabled: {fg3};
menuSeparatorFg: {border};
scrollBarBg: #ffffff20;
scrollBarBgOver: #ffffff40;
scrollBg: #ffffff10;
scrollBgOver: #ffffff20;

// Title bar
titleBg: {topbar};
titleShadow: #00000000;
titleButtonFg: {fg2};
titleButtonBgOver: {bg3};
titleButtonFgOver: {fg};
titleButtonBgActive: {bg3};
titleButtonFgActive: {fg};
titleButtonCloseBg: #00000000;
titleButtonCloseFg: {fg2};
titleButtonCloseBgOver: {danger};
titleButtonCloseFgOver: {fg};
titleButtonCloseBgActive: {danger};
titleButtonCloseFgActive: {fg};
titleFgActive: {fg};
titleFg: {fg2};

// Top bar (chat header)
topBarBg: {topbar};

// Info panel
infoToggle: {fg2};
infoToggleOver: {fg};

// Sidebar / dialogs list
sideBarBg: {sidebar};
sideBarBgActive: {bg3};
sideBarBgRipple: {bg4};
sideBarTextFg: {fg};
sideBarTextFgActive: {fg};
sideBarIconFg: {fg2};
sideBarIconFgActive: {accent};
sideBarShadow: #00000000;
sideBarBadgeBg: {badge};
sideBarBadgeBgMuted: {fg3};
sideBarBadgeFg: {badgeFg};

// Dialogs
dialogsBg: {sidebar};
dialogsNameFg: {fg};
dialogsNameFgActive: {fg};
dialogsChatIconFg: {fg2};
dialogsChatIconFgActive: {fg};
dialogsDateFg: {fg2};
dialogsDateFgActive: {fg2};
dialogsTextFg: {fg2};
dialogsTextFgServiceActive: {fg};
dialogsTextFgActive: {fg2};
dialogsTextFgService: {accent2};
dialogsDraftFg: {danger};
dialogsDraftFgActive: {danger};
dialogsVerifiedIconBg: {accent};
dialogsVerifiedIconFg: {badgeFg};
dialogsSendingIconFg: {fg3};
dialogsSendingIconFgActive: {fg2};
dialogsSentIconFg: {fg2};
dialogsSentIconFgActive: {fg2};
dialogsUnreadBg: {badge};
dialogsUnreadBgMuted: {fg3};
dialogsUnreadFg: {badgeFg};
dialogsForwardedFg: {fg2};
dialogsForwardedFgActive: {fg2};
dialogsMentionIconFg: {badgeFg};
dialogsMentionIconBg: {badge};
dialogsMentionIconFgActive: {badgeFg};
dialogsMentionIconBgActive: {badge};
dialogsFilterDividerBg: {border};
dialogsFilterResultsFg: {fg2};
dialogsBgOver: {bg3};
dialogsBgActive: {accent};
dialogsRippleBg: {bg4};
dialogsRippleBgActive: {accent2};

// Messages
historyScrollBg: #00000000;
historyScrollBgOver: #00000000;
historyScrollBarBg: #00000000;
historyScrollBarBgOver: #00000000;
historyBackgroundCheckFg: {fg};
historyTextInFg: {msgInFg};
historyTextInFgSelected: {fg};
historyTextOutFg: {msgOutFg};
historyTextOutFgSelected: {fg};

msgInBg: {msgIn};
msgInBgSelected: {bg3};
msgOutBg: {msgOut};
msgOutBgSelected: {accent2};
msgSelectOverlay: #00000020;
msgStickerOverlay: #00000040;
msgInShadow: #0000001a;
msgOutShadow: #0000001a;
msgInShadowSelected: #0000001a;
msgOutShadowSelected: #0000001a;
msgInDateFg: {fg3};
msgInDateFgSelected: {fg2};
msgOutDateFg: {fg3};
msgOutDateFgSelected: {fg2};
msgServiceFg: {fg};
msgServiceBg: #00000054;
msgServiceBgSelected: #00000074;
msgInReplyBarColor: {accent};
msgOutReplyBarColor: {accent};
msgImgReplyBarColor: #ffffff;
msgInReplyBarSelColor: {accent};
msgOutReplyBarSelColor: {accent};
msgInMonoFg: {fg2};
msgOutMonoFg: {accent2};
msgDateImgFg: #ffffff;
msgDateImgBg: #00000054;
msgDateImgBgOver: #00000074;
msgDateImgBgSelected: #00000054;
msgFileThumbLinkInFg: {accent};
msgFileThumbLinkInFgSelected: {fg};
msgFileThumbLinkOutFg: {accent};
msgFileThumbLinkOutFgSelected: {fg};
msgFileInBg: {accent};
msgFileInBgOver: {accent2};
msgFileInBgSelected: {accent};
msgFileOutBg: {accent};
msgFileOutBgOver: {accent2};
msgFileOutBgSelected: {accent};
msgFileNameInFg: {fg};
msgFileNameOutFg: {msgOutFg};
msgFileSizeFg: {fg2};
msgWaveformInActive: {accent};
msgWaveformInActiveSelected: {fg};
msgWaveformOutActive: {accent};
msgWaveformOutActiveSelected: {fg};
msgWaveformInInactive: {fg3};
msgWaveformInInactiveSelected: {fg2};
msgWaveformOutInactive: {fg3};
msgWaveformOutInactiveSelected: {fg2};
msgBotKbOverBgAdd: #ffffff20;
msgBotKbIconFg: {fg2};
msgBotKbRippleBg: #ffffff20;

// Input
historyComposeAreaBg: {bg2};
historyComposeAreaFg: {fg};
historyComposeAreaFgService: {fg2};
historyComposeIconFg: {fg2};
historyComposeIconFgOver: {fg};
historySendIconFg: {accent};
historySendIconFgOver: {accent2};
historyPinnedBg: {bg2};
historyReplyBg: {bg2};
historyReplyIconFg: {accent};
historyReplyCancelFg: {fg2};
historyReplyCancelFgOver: {fg};

inputBg: {bg3};
inputBgOver: {bg4};
inputPlaceholderFg: {fg3};

// Boxes / modals
boxBg: {bg2};
boxTextFg: {fg};
boxTextFgGood: {success};
boxTextFgError: {danger};
boxTitleFg: {fg};
boxSearchBg: {bg3};
boxSearchCancelIconFg: {fg2};
boxSearchCancelIconFgOver: {fg};
boxTitleAdditionalFg: {fg2};
boxTitleCloseFg: {fg2};
boxTitleCloseFgOver: {fg};

// Buttons
activeButtonBg: {accent};
activeButtonBgOver: {accent2};
activeButtonBgRipple: {accent2};
activeButtonFg: {badgeFg};
activeButtonFgOver: {badgeFg};
activeButtonSecondaryFg: {badgeFg};
activeButtonSecondaryFgOver: {badgeFg};
activeLineFgError: {danger};

// Settings
settingsSectionBg: {bg};
settingsSectionFg: {fg2};
settingsIconFg: {fg2};
settingsIconFgOver: {fg};
settingsIconFgActive: {accent};

// Counter badge
counterBg: {badge};
counterFg: {badgeFg};
counterBgOver: {accent2};
counterFgOver: {badgeFg};
counterBgMuted: {fg3};
counterFgMuted: {fg};

// Notifications
notificationsBoxBg: {bg2};
notificationsBoxMonitorFg: {fg};

// Profile
profileStatusFg: {fg2};
profileStatusFgOver: {fg2};
profileVerifiedCheckBg: {accent};
profileVerifiedCheckFg: {badgeFg};
profileAdminStartsFg: {fg2};
""".strip()

# Write ZIP for initial one-time import via Ayugram settings
out_dir = os.path.expanduser("~/.local/share/caelestia")
os.makedirs(out_dir, exist_ok=True)
theme_path = os.path.join(out_dir, "pywal.tdesktop-theme")

buf = io.BytesIO()
with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("colors.tdesktop-theme", palette)
with open(theme_path, "wb") as f:
    f.write(buf.getvalue())

# Write plain palette to the path Telegram watches when "Edit current theme" is active
watch_path = os.path.expanduser(
    "~/.local/share/AyuGramDesktop/tdata/themes/custom.tdesktop-palette"
)
os.makedirs(os.path.dirname(watch_path), exist_ok=True)
with open(watch_path, "w") as f:
    f.write(palette)

print(f"Written to {theme_path} and {watch_path}")
